language: php

php:
    - 5.4

before_script:
    - composer install
    - bash tests/bin/travis_jackrabbit.sh

script: 
  - phpunit --coverage-text
  - php vendor/behat/behat/bin/behat
  - php vendor/bin/phpspec run
